### ISSUE TITLE
Create test suite

### ISSUE THREAD

**Issue by sckott** [rOpenGov/rsunlight#32]

**Comment by Ironholds** [comment]
One blocker I'm running into is embedding an API key. Does anyone have any smart ideas about how to do that without making said key visible? testthat ignores system options unless they're set within the suite, it seems.

**Comment by hrbrmstr** [comment]
Would Hadley's secure https://github.com/hadley/secure package help this? A friend & I have it on the TODO to vet the functionality (we're in infosec) but on the surface it looks fine from a security perspective.

**Comment by sckott** [comment]
@hrbrmstr good idea

the approach i've used recently is to allow users to keep keys in either options or as environment variables, and pass a secured env var to CI's like Travis-CI, seems to work, e.g., 

- key checker: https://github.com/ropensci/rgauges/blob/master/R/zzz.R#L21-L23
- test file https://github.com/ropensci/rgauges/blob/master/tests/testthat/test_gs_traffic.R#L3
- the secure env var on travis for the same pkg: https://travis-ci.org/ropensci/rgauges/builds/45706255#L78

**Comment by leeper** [comment]
@sckott Is that implementing what is described here: http://docs.travis-ci.com/user/environment-variables/#Secure-Variables?

**Comment by sckott** [comment]
@leeper yeah, so in the repo locally i do something like `travis encrypt GAUGES_KEY=<my key>`

**Comment by sckott** [comment]
definitely haven't filled out test suite yet, but really need to get update to cran for httr related fixes and cran requested other changes. closing this, opening a new issue to finish off test suite for next milestone
